Add CORS support to sda-auth #minor
neicnordic/sda-auth pull request #147
Opened 2022-05-20 06:43 UTC by norling

This PR adds Cross-Origin Resourse Sharing support to the sda-auth service, as well as a CORS testing page to the dev-server.

2022-06-02 10:35 UTC, aaperis requested changes
I tried the minimal login test site but the Login gave `error: redirect_uri_mismatch
`. Could it be something missing from the configuration?

2022-06-02 10:35 UTC, aaperis commented on README.md
> +openssl genrsa -out keys/sign-rsa-jwt.key 2048
```suggestion
openssl genrsa -out keys/sign-rsa-jwt.key 2048  && chmod 664 keys/sign-rsa-jwt.key
```

2022-06-07 06:49 UTC, norling commented
Good catch! :) I had indeed missed documenting that you need to update the `CLIENT_REDIRECT_URI` to use the CORS login.

2022-06-07 07:20 UTC, aaperis approved these changes
Looks good :-)

2022-07-18 06:31 UTC, dbampalikis approved these changes
Apart for some really minor comments, it looks good!

2022-07-18 06:31 UTC, dbampalikis commented on README.md
> +This servce can be run as a backend only, and in the case where the frontend
```suggestion
This service can be run as a backend only, and in the case where the frontend
```

2022-07-18 06:31 UTC, dbampalikis commented on README.md
> +must be updated by settings `CLIENT_REDIRECT_URI` (under
```suggestion
must be updated by setting the `CLIENT_REDIRECT_URI` (under
```

2022-07-18 06:31 UTC, dbampalikis commented on README.md
> +restarted.
```suggestion
`services/oidc/environment`) to `http://localhost:8000` and restart the server.
```

2022-07-18 06:31 UTC, dbampalikis commented on main.go
>  // getElixirLogin authenticates the user with return values from the elixir
```suggestion
// elixirLogin authenticates the user with return values from the elixir
```

2022-07-18 09:58 UTC, merged