Refactor JWT signing function
neicnordic/sda-auth pull request #172
Opened 2022-11-08 06:46 UTC by jbygdell

* Creates unified JWT signing function so the tokens look similar for both EGA and RS-AAI
* Removes old EGA JWT function
* Removes old Elixir JWT function
* Fixes dev environment
* Deprecates `io/ioutil`
* Start HTTP server with timouts
* Update to GO 1.19

2022-11-10 14:50 UTC, norling approved these changes
some minor things, otherwise I think it's good! jwt's aren't my strong suit though

2022-11-14 13:59 UTC, aaperis commented
Tried to run it with the compose file but `auth` failed with:
`time="2022-11-14T13:57:31Z" level=error msg="State of incoming request (4636d955-f40f-4e17-a139-3b1af81d40b2) does not match with your session's state ()"` . Seems the cookie is not being written properly, but don't know why.

2022-11-14 14:02 UTC, aaperis requested changes
it is definitely much clearer now but some issues need another look :)

2022-11-14 14:02 UTC, aaperis commented on config.yaml
> -  jwtPrivateKey: "keys/sign-rsa-jwt.key"
Since these keys are not used anymore, `readme` needs to be updated accordingly.

2022-11-14 18:04 UTC, aaperis commented on elixir.go
> -	}
With this out, we do not validate the elixir token against the jwk endpoint anymore.

2022-11-15 06:55 UTC, jbygdell commented on elixir.go
> -	}
This is a prefect example of misplaced code, this should be in the OIDC authentication section

2022-11-15 07:58 UTC, aaperis approved these changes

2022-11-24 13:18 UTC, dbampalikis approved these changes

2022-11-24 13:18 UTC, merged