Feature/opt to serve original jwt
neicnordic/sda-auth pull request #208
Opened 2023-03-31 05:24 UTC by aaperis

This PR makes resigning of JWTs a configurable option. In this way,

- if `sda-auth` is  deployed with `resignJwt`=`false`, then the original (raw) token will be served instead i.e. the raw LS AAI token.

- if `resignJwt`=`true`, it will continue working as before i.e. serve re-signed tokens with our own key.

-  `resignJwt` defaults to `true` so that the service works as before if not set. 

Note that the served `s3cfg` file will hold the same token that is served through the webui.

The go testsuite is updated accordingly.

Closes #201.

2023-03-31 05:43 UTC, jbygdell requested changes

2023-03-31 05:43 UTC, jbygdell commented on elixir_test.go
> +		assert.NotEmpty(suite.T(), expDate, "Validation failed but without returning errors")
This is not enough, we need to verify that the `expDate` really is what it should be.

We also need to add a test where the token is expired.

2023-03-31 05:43 UTC, jbygdell commented on elixir.go
> +	expireDate := time.Unix(int64(d), 0)
```suggestion
	if !ok {
		return nil, "", fmt.Errorf("failed to read expiration date from token")
	}
	expireDate := time.Unix(int64(d), 0)
```

A valid token must have an expiration date, if we can't read that we need to throw an error.

2023-03-31 05:43 UTC, jbygdell commented on elixir.go
> +	d, ok := token.Claims.(jwt.MapClaims)["exp"].(float64)
Isn't the returned date in unix format i.e. `int64`

2023-04-04 11:25 UTC, aaperis commented on elixir_test.go
> +		assert.NotEmpty(suite.T(), expDate, "Validation failed but without returning errors")
Agreed and done.

2023-04-04 11:28 UTC, aaperis commented on elixir.go
> +	expireDate := time.Unix(int64(d), 0)
The signature validation that was in place already did an implicit date validation. However, I agree with the point and I adedd some logic to validate dates explicitly and throw errors :)

2023-04-04 11:30 UTC, aaperis commented on elixir.go
> +	d, ok := token.Claims.(jwt.MapClaims)["exp"].(float64)
Good point and good catch, but apparently it can be also `float64`. I added a type switch to cover both cases.

2023-04-04 12:54 UTC, kostas-kou approved these changes

2023-04-04 13:13 UTC, jbygdell approved these changes

2023-04-04 13:25 UTC, norling approved these changes

2023-04-04 13:27 UTC, merged